name: Generate Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  doc-build:
    name: Build Docs and Publish on Pages
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: OffRouteMap
      DOC_OUTPUT_DIR: _site
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Generate basics from README and templates
        run: |
           mv README.md index.md
           cp docs/docfx.json.tmpl docfx.json
           sed -i "s|{{PROJECT_NAME}}|${{ env.PROJECT_NAME }}|g" docfx.json
           sed -i "s|{{DOC_OUTPUT_DIR}}|${{ env.DOC_OUTPUT_DIR }}|g" docfx.json
           cp docs/toc.yml.tmpl docs/toc.yml
           sed -i "s|{{PROJECT_NAME}}|${{ env.PROJECT_NAME }}|g" docs/toc.yml
    
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.DOC_OUTPUT_DIR }}
          