name: Dev Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  doc-build:
    name: Build Docs
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: OffRouteMap
      DOC_OUTPUT_DIR: _site
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Generate basics from README and templates
        run: |
           mv README.md index.md
           cp docs/docfx.json.tmpl docfx.json
           sed -i "s|{{PROJECT_NAME}}|${{ env.PROJECT_NAME }}|g" docfx.json
           sed -i "s|{{DOC_OUTPUT_DIR}}|${{ env.DOC_OUTPUT_DIR }}|g" docfx.json
           cp docs/filterConfig.yml.tmpl filterConfig.yml
           sed -i "s|{{PROJECT_NAME}}|${{ env.PROJECT_NAME }}|g" filterConfig.yml

      - name: Generate docs
        run: |
           docfx metadata
           docfx build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: ${{ env.DOC_OUTPUT_DIR }}