name: .NET 8

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      PROJECT_NAME: OffRouteMap
    steps:
      - uses: actions/checkout@v5

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ${env.PROJECT_NAME}.csproj -c Release --self-contained true -r win-x64 /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true -o publish

      - name: Create Release and Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: 'Release ${{ github.ref }}'
          draft: false
          prerelease: false
          files: publish/${{ env.PROJECT_NAME }}.exe
