name: .NET Core Desktop

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: dotnet publish -c Release --self-contained true /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true -o publish
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-app-artifacts
          path: publish/
