name: Tests and Coverage

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: Build Tests and Coverage
    runs-on: windows-latest
    env:
      PROJECT_NAME: OffRouteMap
      COVERAGE_OUTPUT_DIR: coveragereport

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests and collect Coverage
        run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test-results.trx" --results-directory ./TestResults --collect:"XPlat Code Coverage"

      - name: Publish Test Report to GitHub UI
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Tests
          path: ./TestResults/test-results.trx
          reporter: dotnet-trx

      - name: Generate HTML Coverage Report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.5
        with:
          reports: 'TestResults/**/coverage.cobertura.xml'
          targetdir: '${{ env.COVERAGE_OUTPUT_DIR }}'
          reporttypes: 'HtmlInline;Cobertura'

      - name: Upload Coverage Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Code-Coverage-Report
          path: ${{ env.COVERAGE_OUTPUT_DIR }}